RUNTIME_ERROR:
  # General Parameter Errors (1000 series)
  1001: "Invalid 'eps': must be a positive numeric scalar."
  1002: "Invalid 'min_samples': must be a positive integer scalar."
  1003: "Invalid 'metric': must be a character string."
  1004: "Invalid 'metric_params': must be NULL or a list."
  1005: "Invalid 'algorithm': must be a character string."
  1006: "Invalid 'leaf_size': must be a positive integer scalar."
  1007: "Invalid 'p': must be a positive numeric scalar."
  1008: "Invalid 'n_jobs': must be an integer scalar."

  # Input Data Errors (2000 series)
  2001: "Invalid 'X': must be a matrix or data frame."
  2002: "Invalid 'sample_weight': must be a numeric vector with the same length as the number of rows in 'X'."

  # Runtime Execution Errors (3000 series)
  3000: "Error occurred during DBSCAN execution."
  3001: "DBSCAN clustering failed due to insufficient memory."
  3002: "Invalid distance metric used during DBSCAN execution."
  3003: "Parallel computation failed due to invalid 'n_jobs' configuration."

  # Result Parsing Errors (4000 series)
  4001: "Failed to compute cluster labels. Check input data or parameters."
  4002: "Failed to compute core sample indices. Internal computation error."
  4003: "Output result parsing failed. DBSCAN fit might have encountered an issue."

  # Unclassified Errors (5000 series)
  5001: "Unknown error encountered during DBSCAN initialization."
  5002: "Unexpected error occurred during DBSCAN clustering. Check logs for details."
